spring:
  datasource:
    url: jdbc:mysql://localhost:3306/telecom_db
    username: root
    password: #Verma119427
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


  redis:
    host: localhost
    port: 6379
